#
#   _____ _                 _       _____                          _____         _ _       _
#  / ____(_)               | |     / ____|                        / ____|       (_) |     | |
# | (___  _ _ __ ___  _ __ | | ___| (___   ___ _ ____   _____ _ _| (_____      ___| |_ ___| |__   ___ _ __
#  \___ \| | '_ ` _ \| '_ \| |/ _ \\___ \ / _ \ '__\ \ / / _ \ '__\___ \ \ /\ / / | __/ __| '_ \ / _ \ '__|
#  ____) | | | | | | | |_) | |  __/____) |  __/ |   \ V /  __/ |  ____) \ V  V /| | || (__| | | |  __/ |
# |_____/|_|_| |_| |_| .__/|_|\___|_____/ \___|_|    \_/ \___|_| |_____/ \_/\_/ |_|\__\___|_| |_|\___|_|
#                    | |
#                    |_|
#
# Version 1.0 by Dwarslooper
#

servers:
  admin-server:
    command: joinadminserver # The command to join the server
    restricted: true # If this server is restricted. If yes, the permission specified below is required.
    permission: my.admin.permission # The permission needed to join this server, if restricted. Otherwise, you can just remove this line.